#if !defined(AFX_CANDLESERIES_H__4BE02FB3_0229_11D2_AE48_00400141862D__INCLUDED_)
#define AFX_CANDLESERIES_H__4BE02FB3_0229_11D2_AE48_00400141862D__INCLUDED_

#if _MSC_VER >= 1000
#pragma once
#endif // _MSC_VER >= 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


// Dispatch interfaces referenced by this interface
class CPointer;
class CValueList;

/////////////////////////////////////////////////////////////////////////////
// CCandleSeries wrapper class

class CCandleSeries : public COleDispatchDriver
{
public:
	CCandleSeries() {}		// Calls COleDispatchDriver default constructor
	CCandleSeries(LPDISPATCH pDispatch) : COleDispatchDriver(pDispatch) {}
	CCandleSeries(const CCandleSeries& dispatchSrc) : COleDispatchDriver(dispatchSrc) {}

// Attributes
public:

// Operations
public:
	CPointer GetPointer();
	long GetCandleStyle();
	void SetCandleStyle(long nNewValue);
	long GetCandleWidth();
	void SetCandleWidth(long nNewValue);
	CValueList GetCloseValues();
	CValueList GetDateValues();
	unsigned long GetDownCloseColor();
	void SetDownCloseColor(unsigned long newValue);
	CValueList GetHighValues();
	CValueList GetLowValues();
	CValueList GetOpenValues();
	BOOL GetShowCloseTick();
	void SetShowCloseTick(BOOL bNewValue);
	BOOL GetShowOpenTick();
	void SetShowOpenTick(BOOL bNewValue);
	unsigned long GetUpCloseColor();
	void SetUpCloseColor(unsigned long newValue);
	long AddCandle(double ADate, double AOpen, double AHigh, double ALow, double AClose);
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Developer Studio will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_CANDLESERIES_H__4BE02FB3_0229_11D2_AE48_00400141862D__INCLUDED_)
