// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


#include "stdafx.h"
#include "pointseries.h"

// Dispatch interfaces referenced by this interface
#include "Pointer.h"


/////////////////////////////////////////////////////////////////////////////
// CPointSeries properties

/////////////////////////////////////////////////////////////////////////////
// CPointSeries operations

CPointer CPointSeries::GetPointer()
{
	LPDISPATCH pDispatch;
	InvokeHelper(0x1, DISPATCH_PROPERTYGET, VT_DISPATCH, (void*)&pDispatch, NULL);
	return CPointer(pDispatch);
}
