#if !defined(AFX_POINTSERIES_H__4BE02FB9_0229_11D2_AE48_00400141862D__INCLUDED_)
#define AFX_POINTSERIES_H__4BE02FB9_0229_11D2_AE48_00400141862D__INCLUDED_

#if _MSC_VER >= 1000
#pragma once
#endif // _MSC_VER >= 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


// Dispatch interfaces referenced by this interface
class CPointer;

/////////////////////////////////////////////////////////////////////////////
// CPointSeries wrapper class

class CPointSeries : public COleDispatchDriver
{
public:
	CPointSeries() {}		// Calls COleDispatchDriver default constructor
	CPointSeries(LPDISPATCH pDispatch) : COleDispatchDriver(pDispatch) {}
	CPointSeries(const CPointSeries& dispatchSrc) : COleDispatchDriver(dispatchSrc) {}

// Attributes
public:

// Operations
public:
	CPointer GetPointer();
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Developer Studio will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_POINTSERIES_H__4BE02FB9_0229_11D2_AE48_00400141862D__INCLUDED_)
