#if !defined(AFX_POLARSERIES_H__4BE02FD0_0229_11D2_AE48_00400141862D__INCLUDED_)
#define AFX_POLARSERIES_H__4BE02FD0_0229_11D2_AE48_00400141862D__INCLUDED_

#if _MSC_VER >= 1000
#pragma once
#endif // _MSC_VER >= 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


// Dispatch interfaces referenced by this interface
class CPen1;
class CPointer;
class CValueList;

/////////////////////////////////////////////////////////////////////////////
// CPolarSeries wrapper class

class CPolarSeries : public COleDispatchDriver
{
public:
	CPolarSeries() {}		// Calls COleDispatchDriver default constructor
	CPolarSeries(LPDISPATCH pDispatch) : COleDispatchDriver(pDispatch) {}
	CPolarSeries(const CPolarSeries& dispatchSrc) : COleDispatchDriver(dispatchSrc) {}

// Attributes
public:

// Operations
public:
	long GetXRadius();
	void SetXRadius(long nNewValue);
	long GetYRadius();
	void SetYRadius(long nNewValue);
	CPen1 GetCirclePen();
	long GetXCenter();
	long GetYCenter();
	long GetCircleWidth();
	long GetCircleHeight();
	unsigned long GetCircleBackColor();
	void SetCircleBackColor(unsigned long newValue);
	BOOL GetCircled();
	void SetCircled(BOOL bNewValue);
	long GetRotationAngle();
	void SetRotationAngle(long nNewValue);
	void AngleToPoint(double Angle, double AXRadius, double AYRadius, long* X, long* Y);
	double PointToAngle(long X, long Y);
	double GetAngleIncrement();
	void SetAngleIncrement(double newValue);
	BOOL GetCloseCircle();
	void SetCloseCircle(BOOL bNewValue);
	CPen1 GetPen();
	CPointer GetPointer();
	double GetRadiusIncrement();
	void SetRadiusIncrement(double newValue);
	CValueList GetAngleValues();
	CValueList GetRadiusValues();
	long AddPolar(double Angle, double Value, LPCTSTR ALabel, unsigned long AColor);
	void DrawRing(double Value);
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Developer Studio will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_POLARSERIES_H__4BE02FD0_0229_11D2_AE48_00400141862D__INCLUDED_)
