//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by CTI Demo.rc
//
#define IDD_ABOUTBOX                    100
#define IDD_CTIDEMO_FORM                101
#define IDD_PROPPAGE_ONE                107
#define IDR_MAINFRAME                   128
#define IDR_CTIDEMTYPE                  129
#define IDD_DIALOG_PSYCH                130
#define IDD_DIALOG_MERKEL               131
#define IDD_DIALOG_CURVE                132
#define IDB_SPLASH                      133
#define IDD_PROPPAGE_TWO                133
#define IDB_BITMAP_GRAPH                134
#define IDD_PROPPAGE_THREE              134
#define IDD_TEXTPAGE                    140
#define IDC_TEXT                        141
#define IDC_HEIGHT                      142
#define IDC_BOLD                        143
#define IDC_ITALIC                      144
#define IDD_PRINT_QUERY                 146
#define IDD_MULTIEDIT                   149
#define IDB_BW_LOGO                     150
#define IDM_C0                          150
#define IDB_256_LOGO                    151
#define IDB_HICOLOR_LOGO                151
#define IDM_C1                          151
#define IDM_C2                          152
#define IDB_256COLOR_LOGO               153
#define IDM_C3                          153
#define IDD_PRINT_PREVIEW               154
#define IDM_C4                          154
#define IDM_C5                          155
#define IDM_C6                          156
#define IDD_PROPPAGE_FOUR               156
#define IDM_C7                          157
#define IDD_DIALOG1                     157
#define IDD_DIALOG_PERFORMANCE_INPUT    157
#define IDM_C8                          158
#define IDD_DIALOG_NEW_TEST_FLOW        158
#define IDM_C9                          159
#define IDD_DIALOG_NEW_TEST             159
#define IDM_CA                          160
#define IDM_CB                          161
#define IDD_DIALOG_PERF_CURVES          161
#define IDM_CC                          162
#define IDM_CD                          163
#define IDD_DIALOG_NEW_PERF_FILE        163
#define IDM_CE                          164
#define IDD_PROPPAGE_ZERO               164
#define IDM_CF                          165
#define IDR_MENU_FLOWS                  165
#define IDD_PRINT_PERF_REPORT_QUERY     165
#define IDM_D0                          166
#define IDD_DIALOG_NEW_DEMAND_DATA      166
#define IDC_CURSOR1                     166
#define IDM_D1                          167
#define IDM_COEF                        168
#define IDR_INSTALL                     168
#define IDM_LG                          169
#define IDM_ALLON                       180
#define IDM_NONEON                      181
#define IDC_TAB_APPS                    1000
#define IDC_PSYCH_START                 1002
#define IDC_PSYCH_EDIT_PRESSURE         1002
#define IDC_PSYCH_EDIT_DB_TEMP          1003
#define IDC_PSYCH_EDIT_WB_TEMP          1004
#define IDC_PSYCH_RADIO_IP              1005
#define IDC_PSYCH_RADIO_SI              1006
#define IDC_PSYCH_BUTTON                1007
#define IDC_PSYCH_STATIC_PRESSURE_UNITS 1008
#define IDC_PSYCH_STATIC_DBTEMP_UNITS   1009
#define IDC_PSYCH_STATIC_WBTEMP_UNITS   1010
#define IDC_PSYCH_STATIC_UNITS          1011
#define IDC_PSYCH_STATIC_PRESSURE_LABEL 1012
#define IDC_PSYCH_STATIC_DBTEMP_LABEL   1013
#define IDC_PSYCH_STATIC_PRESSURE_LABEL2 1013
#define IDC_PSYCH_STATIC_WBTEMP_LABEL   1014
#define IDC_PSYCH_STATIC_PRESSURE_LABEL3 1014
#define IDC_PSYCH_LIST_RESULTS          1015
#define IDC_PSYCH_END                   1015
#define IDC_MERKEL_START                1016
#define IDC_MERKEL_STATIC_T1            1016
#define IDC_PSYCH_STATIC_PRESSURE_LABEL4 1016
#define IDC_MERKEL_STATIC_T2            1017
#define IDC_PSYCH_STATIC_PRESSURE_LABEL5 1017
#define IDC_MERKEL_STATIC_WBT           1018
#define IDC_MERKEL_STATIC_LG            1019
#define IDC_MERKEL_EDIT_T1              1020
#define IDC_DEMO_STATIC_FDP             1020
#define IDC_MERKEL_EDIT_T2              1021
#define IDC_MERKEL_EDIT_WBT             1022
#define IDC_MERKEL_EDIT_LG              1023
#define IDC_MERKEL_STATIC_T1_UNITS      1024
#define IDC_MERKEL_STATIC_T2_UNITS      1025
#define IDC_MERKEL_STATIC_WBT_UNITS     1026
#define IDC_MERKEL_BUTTON_RECALC        1027
#define IDC_DEMO_STATIC_WBT             1027
#define IDC_MERKEL_STATIC_RESULTS       1028
#define IDC_DEMO_STATIC_DBT             1028
#define IDC_MERKEL_EDIT_RESULTS         1029
#define IDC_MERKEL_END                  1029
#define IDC_MERKEL_STATIC_WBT_UNITS2    1030
#define IDC_MERKEL_EDIT_ALTITUDE        1030
#define IDC_CURVE_START                 1031
#define IDC_CURVE_BUTTON_RECALC         1031
#define IDC_MERKEL_STATIC_ALTITUDE      1031
#define IDC_CURVE_STATIC_WBT_LABEL      1032
#define IDC_CURVE_STATIC_RANGE_LABEL    1033
#define IDC_CURVE_EDIT_WBT              1034
#define IDC_CURVE_EDIT_RANGE            1035
#define IDC_CURVE_STATIC_WBT_UNITS      1036
#define IDC_CURVE_STATIC_RANGE_UNITS    1037
#define IDC_TCHART_GRAPH                1038
#define IDC_STATIC_CURVE_FILL           1039
#define IDC_EDIT_CURVE_C1               1040
#define IDC_EDIT_CURVE_C2               1041
#define IDC_STATIC_CURVE_C1             1042
#define IDC_STATIC_CURVE_C2             1043
#define IDC_CURVE_END                   1043
#define IDC_CURVE_EDIT_ALTITUDE         1044
#define IDC_CURVE_STATIC_RANGE_LABEL2   1045
#define IDC_CURVE_STATIC_RANGE_UNITS2   1046
#define IDC_CURVE_STATIC_ALTITUDE_UNITS 1046
#define IDC_EDIT_CURVE_KAVL             1047
#define IDC_EDIT_CURVE_LG               1048
#define IDC_STATIC_CURVE_C3             1049
#define IDC_STATIC_CURVE_C4             1050
#define IDC_PSYCH_MENU_CAPTION          1052
#define IDC_PSYCH_RADIO_ITEM1           1057
#define IDC_PSYCH_RADIO_ITEM3           1058
#define IDC_PSYCH_RADIO_ITEM4           1059
#define IDC_EDIT_COPYRIGHT              1061
#define IDC_STATIC_BORDER               1061
#define IDC_STATIC_VERSION              1062
#define IDC_OUTLINE                     1063
#define IDC_STATIC_CTI                  1064
#define IDC_CURSOR_HAND                 1065
#define IDC_RICHEDIT1                   1065
#define IDC_RICHEDIT2                   1066
#define IDC_SPIN_MIN                    1070
#define IDC_SPIN_MAX                    1071
#define IDC_EDIT_MIN                    1072
#define IDC_EDIT_MAX                    1073
#define IDC_EDIT1                       1077
#define IDC_DESC                        1077
#define IDC_PRINT_DESC                  1077
#define IDC_EDIT_USER1                  1077
#define IDC_EDIT_OWNER_NAME             1077
#define IDC_EDIT_FLOW                   1077
#define IDC_EDIT_NEW_FILE               1077
#define IDC_EDIT_TESTNAME               1077
#define IDC_EDIT_ADJUSTED_FLOW          1077
#define IDC_CHECK1                      1079
#define IDC_CHECK3                      1080
#define IDC_CHECK4                      1081
#define IDC_CHECK5                      1082
#define IDC_CHECK6                      1083
#define IDC_CHECK7                      1084
#define IDC_CHECK8                      1085
#define IDC_CHECK9                      1086
#define IDC_CHECK10                     1087
#define IDC_CHECK11                     1088
#define IDC_CHECK12                     1089
#define IDC_CHECK13                     1090
#define IDC_CHECK14                     1091
#define IDC_CHECK15                     1092
#define IDC_CHECK16                     1093
#define IDC_CHECK17                     1094
#define IDC_CHECK18                     1095
#define IDC_CHECK19                     1096
#define IDC_SERIAL_NUMBER               1099
#define IDC_LG                          1099
#define IDC_CHECK20                     1102
#define IDC_COEF                        1102
#define IDC_ALL                         1103
#define IDC_OFF                         1104
#define IDC_BUTTON_KAVL_APPROACH        1105
#define IDC_KAVL                        1106
#define IDC_USER1                       1107
#define IDC_TARGET_APPROACH             1108
#define IDC_BUTTON_ON                   1109
#define IDC_BUTTON_OFF                  1110
#define IDC_BUTTON_ALTITUDE             1111
#define IDC_EDIT_DESIGN_WATER_FLOW      1120
#define IDC_EDIT_DESIGN_HOT_WATER       1121
#define IDC_EDIT_DESIGN_COLD_WATER      1122
#define IDC_EDIT_DESIGN_WET_BULB        1123
#define IDC_EDIT_DESIGN_DRY_BULB        1124
#define IDC_EDIT_DESIGN_FAN_DRIVER      1125
#define IDC_EDIT_DESIGN_BAROMETRIC_PRESSURE 1126
#define IDC_EDIT_DESIGN_LG              1127
#define IDC_BUTTON_EDIT                 1128
#define IDC_STATIC_OWNER                1129
#define IDC_STATIC_PROJECT              1130
#define IDC_STATIC_LOCATION             1132
#define IDC_STATIC_MANUFACTURER         1133
#define IDC_EDIT_TEST_WATER_FLOW        1134
#define IDC_EDIT_TEST_HOT_WATER         1135
#define IDC_EDIT_TEST_COLD_WATER        1136
#define IDC_EDIT_TEST_WET_BULB          1137
#define IDC_EDIT_TEST_DRY_BULB          1138
#define IDC_EDIT_TEST_FAN_DRIVER        1139
#define IDC_EDIT_TEST_BAROMETRIC_PRESSURE 1140
#define IDC_EDIT_TEST_LG                1141
#define IDC_EDIT_CAPABILITY             1142
#define IDC_BUTTON_VIEW_GRAPH           1143
#define IDC_PERF_BUTTON                 1144
#define IDC_STATIC_UNITS_WATER_FLOW     1145
#define IDC_STATIC_UNITS_HOT_WATER      1146
#define IDC_STATIC_UNITS_COLD_WATER     1147
#define IDC_STATIC_UNITS_WET_BULB       1148
#define IDC_STATIC_UNITS_DRY_BULB       1149
#define IDC_STATIC_UNITS_FAN_DRIVER     1150
#define IDC_STATIC_UNITS_BAROMETRIC_PRESSURE 1151
#define IDC_EDIT_PROJECT_NAME           1152
#define IDC_STATIC_UNITS_ADJUSTED_FLOW  1152
#define IDC_EDIT_LOCATION               1153
#define IDC_STATIC_UNITS_PREDICTED_FLOW 1153
#define IDC_EDIT_MANUFACTURER           1154
#define IDC_COMBO_DATA_FILES            1155
#define IDC_BUTTON_NEW                  1156
#define IDC_COMBO_TEST_LIST             1158
#define IDC_DATETIMEPICKER1             1160
#define IDC_BUTTON_SAVE_TEST_DATA       1161
#define IDC_EDIT_R1                     1201
#define IDC_EDIT_R2                     1202
#define IDC_EDIT_R3                     1203
#define IDC_EDIT_R4                     1204
#define IDC_EDIT_R5                     1205
#define IDC_STATIC_R1                   1211
#define IDC_STATIC_R2                   1212
#define IDC_STATIC_R3                   1213
#define IDC_STATIC_R4                   1214
#define IDC_STATIC_R5                   1215
#define IDC_STATIC_WBT1                 1221
#define IDC_STATIC_WBT2                 1222
#define IDC_STATIC_WBT3                 1223
#define IDC_STATIC_WBT4                 1224
#define IDC_STATIC_WBT5                 1225
#define IDC_STATIC_WBT6                 1226
#define IDC_EDIT_WBT1                   1231
#define IDC_EDIT_WBT2                   1232
#define IDC_EDIT_WBT3                   1233
#define IDC_EDIT_WBT4                   1234
#define IDC_EDIT_WBT5                   1235
#define IDC_EDIT_WBT6                   1236
#define IDC_TAB_FLOWS                   1245
#define IDC_STATIC_GB_RANGE1            1250
#define IDC_EDIT_R1_CWT1                1251
#define IDC_EDIT_R1_CWT2                1252
#define IDC_EDIT_R1_CWT3                1253
#define IDC_EDIT_R1_CWT4                1254
#define IDC_EDIT_R1_CWT5                1255
#define IDC_EDIT_R1_CWT6                1256
#define IDC_STATIC_GB_RANGE2            1280
#define IDC_EDIT_R2_CWT1                1281
#define IDC_EDIT_R2_CWT2                1282
#define IDC_EDIT_R2_CWT3                1283
#define IDC_EDIT_R2_CWT4                1284
#define IDC_EDIT_R2_CWT5                1285
#define IDC_EDIT_R2_CWT6                1286
#define IDC_STATIC_GB_RANGE3            1310
#define IDC_EDIT_R3_CWT1                1311
#define IDC_EDIT_R3_CWT2                1312
#define IDC_EDIT_R3_CWT3                1313
#define IDC_EDIT_R3_CWT4                1314
#define IDC_EDIT_R3_CWT5                1315
#define IDC_EDIT_R3_CWT6                1316
#define IDC_STATIC_GB_RANGE4            1340
#define IDC_EDIT_R4_CWT1                1341
#define IDC_EDIT_R4_CWT2                1342
#define IDC_EDIT_R4_CWT3                1343
#define IDC_EDIT_R4_CWT4                1344
#define IDC_EDIT_R4_CWT5                1345
#define IDC_EDIT_R4_CWT6                1346
#define IDC_STATIC_GB_RANGE5            1370
#define IDC_EDIT_R5_CWT1                1371
#define IDC_EDIT_R5_CWT2                1372
#define IDC_EDIT_R5_CWT3                1373
#define IDC_EDIT_R5_CWT4                1374
#define IDC_EDIT_R5_CWT5                1375
#define IDC_EDIT_R5_CWT6                1376
#define IDC_STATIC_LEGEND               1415
#define IDC_TAB_CURVES                  1416
#define IDC_COMBO_FILE_LIST             1417
#define IDC_EDIT_PREDICTED_FLOW         1418
#define IDC_STATIC_SPECS                1419
#define IDC_STATIC_CURVE                1420
#define IDC_DEMO_STATIC_WFR             1421
#define IDC_DEMO_STATIC_HWT             1422
#define IDC_DEMO_STATIC_CWT             1423
#define IDC_DEMO_STATIC_HWT_UNITS       1424
#define IDC_DEMO_STATIC_WFR_UNITS       1425
#define IDC_DEMO_STATIC_CWT_UNITS       1426
#define IDC_DEMO_STATIC_WBT_UNITS       1427
#define IDC_DEMO_STATIC_WFR_MIN         1428
#define IDC_DEMO_STATIC_WFR_MAX         1429
#define IDC_DEMO_STATIC_HWT_MIN         1430
#define IDC_DEMO_STATIC_CWT_MIN         1431
#define IDC_DEMO_STATIC_WBT_MIN         1432
#define IDC_DEMO_STATIC_LG_MIN          1433
#define IDC_DEMO_STATIC_HWT_MAX         1434
#define IDC_DEMO_STATIC_CWT_MAX         1435
#define IDC_DEMO_STATIC_WBT_MAX         1436
#define IDC_DEMO_STATIC_LG_MAX          1437
#define IDC_DEMO_STATIC_LG              1438
#define IDC_DEMO_STATIC_FDP_MIN         1439
#define IDC_DEMO_STATIC_FDP_MAX         1440
#define IDC_DEMO_STATIC_BP              1441
#define IDC_DEMO_STATIC_BP_MIN          1442
#define IDC_DEMO_STATIC_BP_MAX          1443
#define IDC_DEMO_STATIC_FDP_UNITS       1444
#define IDC_DEMO_STATIC_BP_UNITS        1445
#define IDC_DEMO_STATIC_DBT_UNITS       1446
#define IDC_DEMO_STATIC_DBT_MIN         1447
#define IDC_ABOUT_PROGRAM_NAME          1447
#define IDC_DEMO_STATIC_DBT_MAX         1448
#define IDC_ABOUT_COPYRIGHT             1448
#define IDC_EDIT_COLD_WATER_DEV         1449
#define IDC_STATIC_UNITS_COLD_WATER_DEV 1450
#define IDC_BUTTON_COPY_GRAPH           1451
#define IDC_RADIO_INDUCED               1452
#define IDC_BUTTON_REVERSE              1452
#define IDC_RADIO_FORCED                1453
#define IDC_RADIO_PERF_REPORT           1454
#define IDC_RADIO_DESIGN_DATA           1455
#define IDC_EDIT_DATANAME               1456
#define IDC_BUTTON_SAVE                 1457
#define IDC_ABOUT_COPYRIGHT2            1458
#define IDS_BAROMETRIC_PRESSURE         2000
#define IDS_ALTITUDE                    2001
#define ID_HELPHELP                     32771
#define IDM_MULTIEDIT                   32772
#define ID_DEMAND_CURVES                32773
#define IDM_FLOWTABS_DELETE             32774
#define IDM_FLOWTABS_EDIT               32775
#define IDS_PROPSHEET_CAPTION           57346

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        169
#define _APS_NEXT_COMMAND_VALUE         32776
#define _APS_NEXT_CONTROL_VALUE         1459
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
