// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


#include "stdafx.h"
#include "teefunction.h"

// Dispatch interfaces referenced by this interface
#include "CurveFittingFunction.h"
#include "ExpAvgFunction.h"
#include "MovingAvgFunction.h"


/////////////////////////////////////////////////////////////////////////////
// CTeeFunction properties

/////////////////////////////////////////////////////////////////////////////
// CTeeFunction operations

long CTeeFunction::GetPeriod()
{
	long result;
	InvokeHelper(0x1, DISPATCH_PROPERTYGET, VT_I4, (void*)&result, NULL);
	return result;
}

void CTeeFunction::SetPeriod(long nNewValue)
{
	static BYTE parms[] =
		VTS_I4;
	InvokeHelper(0x1, DISPATCH_PROPERTYPUT, VT_EMPTY, NULL, parms,
		 nNewValue);
}

CCurveFittingFunction CTeeFunction::GetAsCurveFit()
{
	LPDISPATCH pDispatch;
	InvokeHelper(0x2, DISPATCH_PROPERTYGET, VT_DISPATCH, (void*)&pDispatch, NULL);
	return CCurveFittingFunction(pDispatch);
}

CExpAvgFunction CTeeFunction::GetAsExpAvg()
{
	LPDISPATCH pDispatch;
	InvokeHelper(0x3, DISPATCH_PROPERTYGET, VT_DISPATCH, (void*)&pDispatch, NULL);
	return CExpAvgFunction(pDispatch);
}

CMovingAvgFunction CTeeFunction::GetAsMovAvg()
{
	LPDISPATCH pDispatch;
	InvokeHelper(0x4, DISPATCH_PROPERTYGET, VT_DISPATCH, (void*)&pDispatch, NULL);
	return CMovingAvgFunction(pDispatch);
}
