#if !defined(AFX_TEEFUNCTION_H__4BE02FA7_0229_11D2_AE48_00400141862D__INCLUDED_)
#define AFX_TEEFUNCTION_H__4BE02FA7_0229_11D2_AE48_00400141862D__INCLUDED_

#if _MSC_VER >= 1000
#pragma once
#endif // _MSC_VER >= 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


// Dispatch interfaces referenced by this interface
class CCurveFittingFunction;
class CExpAvgFunction;
class CMovingAvgFunction;

/////////////////////////////////////////////////////////////////////////////
// CTeeFunction wrapper class

class CTeeFunction : public COleDispatchDriver
{
public:
	CTeeFunction() {}		// Calls COleDispatchDriver default constructor
	CTeeFunction(LPDISPATCH pDispatch) : COleDispatchDriver(pDispatch) {}
	CTeeFunction(const CTeeFunction& dispatchSrc) : COleDispatchDriver(dispatchSrc) {}

// Attributes
public:

// Operations
public:
	long GetPeriod();
	void SetPeriod(long nNewValue);
	CCurveFittingFunction GetAsCurveFit();
	CExpAvgFunction GetAsExpAvg();
	CMovingAvgFunction GetAsMovAvg();
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Developer Studio will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_TEEFUNCTION_H__4BE02FA7_0229_11D2_AE48_00400141862D__INCLUDED_)
